synaxnet/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Education.Areas.Admin.Controllers
{
    [Area("Admin")]
    
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

synaxnet/Areas/Admin/Controllers/ProductController.cs
using synaxnet.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp.Formats.Jpeg;
using synaxnet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using System.Security.Claims;

namespace synaxnet.Areas.Admin.Controllers
{
    [Area("Admin")]
  
    public class ProductController : Controller
    {
        private readonly string entityName = "Masallar";
        private readonly AppDbContext context;
        private readonly IConfiguration configuration;
        private readonly IWebHostEnvironment webHostEnvironment;

        public ProductController(
            AppDbContext context,
            IConfiguration configuration,
            IWebHostEnvironment webHostEnvironment



            )
        {
            this.context = context;
            this.configuration = configuration;
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> TableData(Guid? id, DataTableParameters parameters)
        {
            var query = context.Products;

            var result = new DataTableResult
            {
                data = await query
                    .Skip(parameters.Start)
                    .Take(parameters.Length)
                    .Select(p => new
                    {
                        p.Id,
                        p.Name,
                        p.Text,
                        p.Photo,
                        dateCreated = p.Date.ToLocalTime().ToShortDateString(),
                    }).ToListAsync(),
                draw = parameters.Draw,
                recordsFiltered = await query.CountAsync(),
                recordsTotal = await query.CountAsync()
            };

            return Json(result);
        }
        public async Task<IActionResult> Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Product model)
        {

            if (model.PhotoFile is not null)
            {
                using var image = await Image.LoadAsync(model.PhotoFile.OpenReadStream());


                image.Mutate(p => p.Resize(new ResizeOptions
                {
                    Size = new Size(200, 200),
                    Mode = ResizeMode.Crop
                }));

                model.Photo = image.ToBase64String(JpegFormat.Instance);

            }




            context.Products.Add(model);
            context.SaveChanges();
            TempData["success"] = "Ürün ekleme işlemi başarıyla tamamlanmıştır";
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = context.Products.Find(id);

            return View(model);


        }
       
        [HttpPost]
        public async Task<IActionResult> Edit(Product model)
        {



            if (model.PhotoFile is not null)
            {
                using var image = await Image.LoadAsync(model.PhotoFile.OpenReadStream());


                image.Mutate(p => p.Resize(new ResizeOptions
                {
                    Size = new Size(250, 250),
                    Mode = ResizeMode.Crop
                }));

                model.Photo = image.ToBase64String(JpegFormat.Instance);

            }




            context.Products.Add(model);

            context.Products.Update(model);
            context.SaveChanges();
            TempData["success"] = "Ürün güncelleme işlemi başarıyla tamamlanmıştır";
            return RedirectToAction(nameof(Index));





        }

        public IActionResult Delete(Guid id)
        {
            var model = context.Products.Find(id);
            context.Products.Remove(model);
            context.SaveChanges();
            TempData["success"] = "Ürün silme işlemi başarıyla tamamlanmıştır";
            return RedirectToAction(nameof(Index));
        }
    }
}

synaxnet/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using synaxnet.Data;
using synaxnet.Models;

namespace synaxnet.Controllers
{
    public class OrderController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AppDbContext context;

        public OrderController(ILogger<HomeController> logger, AppDbContext context)
        {
            _logger = logger;
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Order()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Order(OrderViewModel model, Guid id)
        {
            var product = await context.Products.SingleOrDefaultAsync(p => p.Id == id);
            var ipAddress = HttpContext.Request.Headers["X-Forwarded-For"].FirstOrDefault();
            if (string.IsNullOrEmpty(ipAddress))
            {
                ipAddress = HttpContext.Connection.RemoteIpAddress?.ToString();
            }


            var order = new Order
                {
                    Name = model.Name,
                    Address = model.Address,
                    City = model.City,
                    PhoneNumber = model.PhoneNumber,
                    Email = model.Email,
                    IpAdres = HttpContext.Connection.RemoteIpAddress.ToString(),
                    Status=OrderStatus.New

                    
                };

                context.Orders.Add(order);
                await context.SaveChangesAsync();

                TempData["success"] = "Ürün ekleme işlemi başarıyla tamamlanmıştır";
                return View();
           
        }

    }
}

synaxnet/Areas/Admin/Views/Shared/_DataTablesPartial.cshtml
<link href="~/admin/vendors/datatables.net-bs5/datatables.bootstrap5.css" rel="stylesheet" />
<script src="~/admin/vendors/datatables.net-bs5/datatables.bootstrap5.js"></script>
<script>

    function createDatatable(u, c, e) {
        return $('.datatable').DataTable({
            processing: true,
            serverSide: true,
            scrollX: true,

            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.13.4/i18n/tr.json',
            },
            ajax: {
                url: u,
                method: 'GET'
            },
            columns: c,
            
        }).on('draw', e);
    }

</script>

synaxnet/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/Admin/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/Admin/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/Admin/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/Admin/vendors/datatables.net-bs5/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/Admin/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/Admin/css/vertical-layout-light/style.css">
    <!-- endinject -->

</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
               
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="icon-menu"></span>
                </button>
                <ul class="navbar-nav navbar-nav-center">
                    <li class="nav-item nav-search d-none d-lg-block">
                        <div class="input-group">
                            <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
                                <span class="input-group-text" id="search">
                                    <i class="icon-search"></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
                        </div>
                    </li>
                    <form id="logoutForm" asp-controller="Account" asp-action="Logout" asp-area="" method="post" class="form-inline">
        @Html.AntiForgeryToken()

        <a id="logoutLink" href="javascript:document.getElementById('logoutForm').submit()" class="nav-link">Logout</a>
    </form>
                </ul>

                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="icon-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_settings-panel.html -->
            <!-- partial -->
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav user-select-none">

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                            <i class="ti-world menu-icon"></i>
                            <span class="menu-title">Dashboard</span>
                        </a>
                    </li>





                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#content" aria-expanded="false" aria-controls="content">
                            <i class="ti-write menu-icon"></i>
                            <span class="menu-title">Content</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="content">
                            <ul class="nav flex-column sub-menu">
                                
                                <li class="nav-item"> <a class="nav-link" asp-controller="Product" asp-action="Index">ürünler</a></li>
                                 <li class="nav-item"> <a class="nav-link" asp-controller="Order" asp-action="Index"> siparişler</a></li>
                                 
                            </ul>
                        </div>
                    </li>

                 

                 

                  


                  


                </ul>
            </nav>




            <!-- content -->
            @RenderBody()

            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/Admin/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/Admin/vendors/chart.js/Chart.min.js"></script>
    <script src="~/Admin/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/Admin/vendors/datatables.net-bs5/dataTables.bootstrap4.js"></script>
    <script src="~/Admin/js/dataTables.select.min.js"></script>

    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/Admin/js/off-canvas.js"></script>
    <script src="~/Admin/js/hoverable-collapse.js"></script>
    <script src="~/Admin/js/template.js"></script>
    <script src="~/Admin/js/settings.js"></script>
    <script src="~/Admin/js/todolist.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/Admin/js/dashboard.js"></script>
    <script src="~/Admin/js/Chart.roundedBarCharts.js"></script>
    <!-- End custom js for this page-->
</body>

</html>

      @await RenderSectionAsync("Scripts", required: false)
<script>
    @if (TempData["success"] is not null)
    {
        <text>
            Swal.fire({
                toast: true,
            position: 'top',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton : false,
            timer : 5000
        })
        </text>
    }

    @if (TempData["error"] is not null)
    {
        <text>
            Swal.fire({
                toast: true,
            position: 'top',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton : false,
            timer : 5000
            })
        </text>
    }
</script>

synaxnet/Areas/Admin/Views/Shared/_ToolBarPartial.cshtml
<div >
            <a asp-action="Create" class="btn btn-primary ms-auto">
                <i class="bi bi-plus"></i>
                Yeni Kayıt
            </a>

        </div>
        